name = "worker"
type = "webpack"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [ 
    { binding = "TEST_DATA", id = "" },
    { binding = "WIDGETS", id = "" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


